import React from 'react';
import {
  LayoutDashboard,
  Users,
  FolderKanban,
  Inbox,
  BarChart3,
  Plus,
  ArrowUpRight,
  ArrowDownRight,
  MoreHorizontal,
  Search,
  ChevronDown,
  Download,
  FileText,
  Bell,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  MessageSquare,
  Sparkles,
  Paperclip,
  Send,
  Lightbulb,
  ListTodo,
  Rocket,
  Wand2,
  Mail,
  Star,
  Hand,
  Infinity,
  Filter,
  CalendarDays,
  TrendingUp,
  DollarSign,
  Target,
  Briefcase,
  ListChecks,
  Handshake,
  UsersRound,
  type LucideProps,
} from 'lucide-react';

export const Icons = {
  logo: (props: LucideProps) => <Infinity {...props} />,
  dashboard: LayoutDashboard,
  clients: Users,
  projects: Briefcase,
  deals: Target,
  tasks: ListChecks,
  inbox: Inbox,
  analytics: BarChart3,
  plus: Plus,
  arrowUp: ArrowUpRight,
  arrowDown: ArrowDownRight,
  more: MoreHorizontal,
  search: Search,
  chevronDown: ChevronDown,
  download: Download,
  file: FileText,
  notification: Bell,
  clock: Clock,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alert: AlertCircle,
  note: MessageSquare,
  sparkles: Sparkles,
  attachment: Paperclip,
  send: Send,

  // New Icons
  idea: Lightbulb,
  timeline: Rocket,
  smart: Wand2,
  mail: Mail,
  star: Star,
  hand: Hand,
  filter: Filter,
  calendar: CalendarDays,
  trendingUp: TrendingUp,
  dollarSign: DollarSign,
  folderKanban: FolderKanban,
  leads: Handshake,
  teams: UsersRound,
};
